function fig = fftoptionbox()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

mat1='if get(gco,''value'')==1 || (get(gco,''value'')==0  && get(findobj(''tag'',''RatioHarmonic''),''value'')==0);set(findobj(''tag'',''RatioHarmonic''),''value'',0);set(gco,''value'',1);end';
mat2='if get(gco,''value'')==1 | (get(gco,''value'')==0 & get(findobj(''tag'',''SingleHarmonic''),''value'')==0);set(findobj(''tag'',''SingleHarmonic''),''value'',0);set(gco,''value'',1);end';

h0 = figure('Color',[0.8 0.8 0.8], ...
	'FileName','F:\MATLABR11\user\fftoptionbox.m', ...
	'MenuBar','none', ...
	'Name','FFT Options', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[632 292 182 230], ...
	'Units','Pixels', ...
	'Resize','off', ...
	'Tag','FFTOptions Figure', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'ListboxTop',0, ...
	'Position',[0 0 182 230], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'FontWeight','demi', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[10 160 70 23], ...
	'String','Temporal Frequency', ...
	'Style','text', ...
	'Tag','Label');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.250980392156863 0 0.250980392156863], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[80 160 33 20], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','TempFreqBox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[120 160 20.25 15], ...
	'String','Hz', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'Callback',mat1, ...
	'FontWeight','light', ...
	'ListboxTop',0, ...
	'Position',[4 120 110 15], ...
	'String','Single Harmonic', ...
	'Style','radiobutton', ...
	'Tag','SingleHarmonic', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[130 120 35 20], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','SingHarmnBox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'Callback',mat2, ...
	'ListboxTop',0, ...
	'Position',[4 100 110 15], ...
	'String','Ratio', ...
	'Style','radiobutton', ...
	'Tag','RatioHarmonic');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[100 100 30 20], ...
	'Style','edit', ...
	'Tag','Harmn1Box');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[133 100 9 16.5], ...
	'String','/', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[145 100 30 20], ...
	'Style','edit', ...
	'Tag','Harmn2Box');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'Callback','global choice; choice=1;', ...
	'ListboxTop',0, ...
	'Position',[18 10 140 18], ...
	'String','Continue', ...
	'Tag','FFTContinueButton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.5 0.5], ...
	'FontAngle','italic', ...
	'FontName','Helvetica', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 0], ...
	'ListboxTop',0, ...
	'Position',[0 215 182 15], ...
	'String','FFT Options', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.6 0.6 0.6], ...
	'Callback','vshelp(''FFTOpts'')', ...
	'FontName','Helvetica', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[160 215 15 14.25], ...
	'String','?', ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'ListboxTop',0, ...
	'Position',[4 65 120 15], ...
	'String','Infinity Point = (max) x', ...
	'Style','checkbox', ...
	'Tag','SetInfPoint');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[130 65 35 20], ...
	'Style','edit', ...
	'Tag','InfPointBox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.78 0.78 0.78], ...
	'ListboxTop',0, ...
	'Position',[34.5 37.5 63 14.25], ...
	'String','0/0 Point = (-1) x', ...
	'Style','text', ...
	'Tag','SetNaNPoint');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[130 37.5 35 20], ...
	'Style','edit', ...
	'Tag','ZeroPointBox');
if nargout > 0, fig = h0; end
