function bp = defaultParams()
    bp = struct();
    bp.burn_iter = 0; %The number of burn-in MCMC iterations.
    bp.samp_iter = 2000; %The number of sample MCMC iterations
    bp.k = 3; %initial number of knots
    bp.nf = 500; %The number of evenly spaced points for the grid along which fitted values will be obtained.
    bp.use_logspline = 1; %"true" or "false" to indicate whether Logspline is used for the initial knots. If Logspline is not used, evenly spaced knots are used. Default value = true.
    bp.beta_iter = 3; %Number of iterations for the independence chain on beta for a particular set of knots. It only runs a chain if the initial beta variate is suspect. In this case, the independence chain is run starting from the mle and only the last variate is used. If no beta candidates were accepted, no beta is used although the knot set is not rejected.
	bp.probbd = .4; %Parameter that controls the probability of birth and death candidates. It may be at most 0.5. Larger values increase the probability for birth death candidates. Smaller values increase the probability for knot relocation.
    bp.tau = 50; %Parameter that controls the spread for the knot proposal distribution. A candidate knot is generated by first selecting a current knot t, 0 < t < 1, and then selecting candidate knot ~ beta(t * tau, (1-t) * tau).
    bp.conf_level = .95; %The confidence level for parameter intervals.
    bp.threshold = -10; %Threshhold for determining whether the initial beta variate is suspect. It is suspect if the log acceptance probability is less than the threshhold.

    bp.prior_id = 'UNIFORM';
    bp.dparams = 6; %Poisson_parameter_lambda
    bp.iparams = [1 80];  %lower and upper bounds  
end